#!/usr/bin/env bash
# get ip for subdomain

conf () {
	dig "$1"."$2" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$1"  '{print "The subdomain " s  " is a " $4 " record and points to " $5}'
}

if [ "$#" ==  1 ]
then
	conf 'www' "$1"
	conf 'lb-01' "$1"
	conf 'web-01' "$1"
	conf 'web-02' "$1"

elif [ "$#" == 2 ]
then
	conf "$2" "$1"
fi
