#!/usr/bin/env bash
# install nginx on server and set root

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' > '/var/www/html/index.html'
new_link="server_name _;\n\trewrite ^\/redirect_me http:\/\/nassera.tech permanent;"
sudo sed -i "s/server_name _;/$new_link/" /etc/nginx/sites-available/default
sudo service nginx restart
