#!/usr/bin/env bash
#print Best School 10 times using while loop
# 3 is bad luck 7 is good one
i=0
while [ $i -lt 10 ]
do 
	if [ $i == 3 ]
	then
		echo 'bad luck'	
	elif [ $i == 7 ]
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	(( i++ ))
done
