#!/usr/bin/env bash
#print Best School 10 times using while loop
# theres no good luck only bad as follow, 4 for china
# 9 for japan and 17 fir italy
i=1
while [ $i -le 20 ]
do 
	echo $i
	case $i in
		4)
			echo 'bad luck from China'
			;;
		9)
			echo 'bad luck from Japan'
			;;
		17)
			echo 'bad luck from Italy'
			;;
	esac
	(( i++ ))
done
