#!/usr/bin/env bash
# change server port
sudo sed -i 's/Listen 80/Listen 80\nListen 8080/' /etc/apache2/ports.conf
sudo sed -i 's/<VirtualHost \*:80>/<VirtualHost \*:8080>/' /etc/apache2/sites-enabled/000-default.conf
sudo service apache2 restart
